remote_theme: "mmistakes/minimal-mistakes@4.26.0"
title: ArcTechViews
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site to review the latest tech gadgets and software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arctechviews.blog"
repository: "Eluxifer/techreviews"
favicon: /assets/images/ArcTechViews.png  # Update this path to match your image location

# Add a logo or front page image here
header:
  image: /assets/images/ArcTechViews.png  # Correct path to your image
  image_quality: 85
  image_position: center center
  image_repeat: no-repeat
  image_size: cover

# Build settings
markdown: kramdown
theme: jekyll-theme-primer  # Make sure this theme is what you want to use

# Plugins
plugins:
- jekyll-seo-tag 
- jekyll-coffeescript 
- jekyll-commonmark-ghpages
- jekyll-gist
- jekyll-github-metadata 
- jekyll-paginate
- jekyll-relative-links 
- jekyll-optional-front-matter 
- jekyll-readme-index 
- jekyll-default-layout 
- jekyll-titles-from-headings 
- jekyll-remote-theme 
- jekyll-include-cache

future: true
paginate: 5
paginate_path: "/page:num/"

# Permalinks
permalink: /:year/:month/:day/:title.html
