remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: Tech Reviews Blog
description: Stay updated with the latest tech news and reviews!

plugins:
- jekyll-include-cache
- jekyll-feed
- jekyll-seo-tag
