remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Tech Reviews
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site to review the latest tech gadgets and software.
baseurl: "/techreviews" # the subpath of your site, e.g. /blog
url: "https://eluxifer.github.io/techreviews"
repository: "Eluxifer/techreviews" # Add this line
# Build settings
markdown: kramdown
theme: jekyll-theme-primer

plugins:
- jekyll-seo-tag 
- jekyll-coffeescript 
- jekyll-commonmark-ghpages
- jekyll-gist
- jekyll-github-metadata 
- jekyll-paginate
- jekyll-relative-links 
- jekyll-optional-front-matter 
- jekyll-readme-index 
- jekyll-default-layout 
- jekyll-titles-from-headings 
- jekyll-remote-theme 
- jekyll-include-cache
future: true
paginate: 5
paginate_path: "/page:num/"

