remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: Tech Reviews Blog
description: Stay updated with the latest tech news and reviews!

plugins:
- jekyll-feed
 - jekyll-seo-tag
future: true
paginate: 5
paginate_path: "/page:num/"

